services:
  - type: web
    name: portfolio
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default